server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://192.168.1.72:3306/assignment?serverTimezone=UTC
    username: louis
    password: louis268
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: authservice

mybatis:
  configuration:
    map-underscore-to-camel-case: true

app:
  jwtSecret: your_super_secret_key_that_is_long_enough
  jwtExpirationInMs: 3600000
