server:
  port: 10010
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      config:
        server-addr: 192.168.1.72:8848
      discovery:
        server-addr: 192.168.1.72:8848

    gateway:
      routes:
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**


main:
  web-application-type: reactive