server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.1.72:3306/assignment?serverTimezone=UTC
    username: louis
    password: louis268
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice

mybatis:
  configuration:
    map-underscore-to-camel-case: true