server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.1.72:3306/hotel?serverTimezone=UTC
    username: louis
    password: louis268
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice



  cloud:
    nacos:
      server-addr: 192.168.1.72:8848
      file-extension: yaml
#    compatibility-verifier:
#      enabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

